# Generated by Django 3.0.3 on 2020-05-05 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200428_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='riderBirthData',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
