# Generated by Django 3.0.3 on 2020-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='riderNationality',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='rider',
            name='bikeBrand',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='rider',
            name='bikeModel',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='rider',
            name='riderName',
            field=models.CharField(default='', max_length=60),
        ),
    ]
